//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VCTEntities : DbContext
    {
        public VCTEntities()
            : base("name=VCTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Browser> Browsers { get; set; }
        public virtual DbSet<Environment> Environments { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Resolution> Resolutions { get; set; }
        public virtual DbSet<RunningOS> RunningOS { get; set; }
        public virtual DbSet<RunningSuite> RunningSuites { get; set; }
        public virtual DbSet<RunningTest> RunningTests { get; set; }
        public virtual DbSet<StableFile> StableFiles { get; set; }
        public virtual DbSet<Suite> Suites { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<TestResult> TestResults { get; set; }
    }
}
